baseURL: "https://zer0-star.github.io/blog/"
title: zer0-star's blog
paginate: 5
theme: hugo-PaperMod
defaultContentLanguage: "ja"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

canonifyurls: true

markup:
  highlight:
    lineNos: true
    lineNumbersInTable: false

params:
  env: production
  description: "zer0-star's blog"
  author: zer0-star
  
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  # displayFullLangName: true
  # images: ""
  assets:
    favicon: "favicon.webp"

  profileMode:
    enabled: true
    title: zer0-star's blog
    subtitle: ブログ始めました
    imageUrl: "images/zer0-star.webp"
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: Hi
    Content: Hey!

  socialIcons:
    - name: twitter
      url: "https://twitter.com/0x_zer0star"
    - name: github
      url: "https://github.com/zer0-star"
    - name: atcoder
      url: "https://atcoder.jp/users/zer0star"

taxonomies:
  category: categories
  tag: tags
  series: series

